// GENERATED by scripts/onda_catalog.py — the catalog's Onda components.
import type { ComponentType } from 'react';
import type { ZodTypeAny } from 'zod';

import { Terminal } from '../../../../vox/remotion/_bench/onda/registry/components/terminal/Terminal';
import { terminalSchema } from '../../../../vox/remotion/_bench/onda/registry/components/terminal/schema';
import { CodeBlock } from '../../../../vox/remotion/_bench/onda/registry/components/code-block/CodeBlock';
import { codeBlockSchema } from '../../../../vox/remotion/_bench/onda/registry/components/code-block/schema';
import { CodeDiff } from '../../../../vox/remotion/_bench/onda/registry/components/code-diff/CodeDiff';
import { diffLineSchema } from '../../../../vox/remotion/_bench/onda/registry/components/code-diff/schema';
import { MatrixDecode } from '../../../../vox/remotion/_bench/onda/registry/components/matrix-decode/MatrixDecode';
import { matrixDecodeSchema } from '../../../../vox/remotion/_bench/onda/registry/components/matrix-decode/schema';
import { NodeGraph } from '../../../../vox/remotion/_bench/onda/registry/components/node-graph/NodeGraph';
import { nodeGraphSchema } from '../../../../vox/remotion/_bench/onda/registry/components/node-graph/schema';
import { DynamicGrid } from '../../../../vox/remotion/_bench/onda/registry/components/dynamic-grid/DynamicGrid';
import { dynamicGridSchema } from '../../../../vox/remotion/_bench/onda/registry/components/dynamic-grid/schema';
import { ProgressSteps } from '../../../../vox/remotion/_bench/onda/registry/components/progress-steps/ProgressSteps';
import { progressStepsSchema } from '../../../../vox/remotion/_bench/onda/registry/components/progress-steps/schema';
import { SplitScreen } from '../../../../vox/remotion/_bench/onda/registry/components/split-screen/SplitScreen';
import { splitScreenSchema } from '../../../../vox/remotion/_bench/onda/registry/components/split-screen/schema';
import { VideoClip } from '../../../../vox/remotion/_bench/onda/registry/components/video-clip/VideoClip';
import { videoClipSchema } from '../../../../vox/remotion/_bench/onda/registry/components/video-clip/schema';
import { AudioClip } from '../../../../vox/remotion/_bench/onda/registry/components/audio-clip/AudioClip';
import { audioClipSchema } from '../../../../vox/remotion/_bench/onda/registry/components/audio-clip/schema';
import { AudioVisualizer } from '../../../../vox/remotion/_bench/onda/registry/components/audio-visualizer/AudioVisualizer';
import { audioVisualizerSchema } from '../../../../vox/remotion/_bench/onda/registry/components/audio-visualizer/schema';
import { Captions } from '../../../../vox/remotion/_bench/onda/registry/components/captions/Captions';
import { captionsSchema } from '../../../../vox/remotion/_bench/onda/registry/components/captions/schema';
import { PulsingIndicator } from '../../../../vox/remotion/_bench/onda/registry/components/pulsing-indicator/PulsingIndicator';
import { pulsingIndicatorSchema } from '../../../../vox/remotion/_bench/onda/registry/components/pulsing-indicator/schema';
import { Confetti } from '../../../../vox/remotion/_bench/onda/registry/components/confetti/Confetti';
import { confettiSchema } from '../../../../vox/remotion/_bench/onda/registry/components/confetti/schema';
import { RgbGlitchText } from '../../../../vox/remotion/_bench/onda/registry/components/rgb-glitch-text/RgbGlitchText';
import { rgbGlitchTextSchema } from '../../../../vox/remotion/_bench/onda/registry/components/rgb-glitch-text/schema';
import { GradientShift } from '../../../../vox/remotion/_bench/onda/registry/components/gradient-shift/GradientShift';
import { gradientShiftSchema } from '../../../../vox/remotion/_bench/onda/registry/components/gradient-shift/schema';
import { GrainOverlay } from '../../../../vox/remotion/_bench/onda/registry/components/grain-overlay/GrainOverlay';
import { grainOverlaySchema } from '../../../../vox/remotion/_bench/onda/registry/components/grain-overlay/schema';
import { Vignette } from '../../../../vox/remotion/_bench/onda/registry/components/vignette/Vignette';
import { vignetteSchema } from '../../../../vox/remotion/_bench/onda/registry/components/vignette/schema';
import { CameraShake } from '../../../../vox/remotion/_bench/onda/registry/components/camera-shake/CameraShake';
import { cameraShakeSchema } from '../../../../vox/remotion/_bench/onda/registry/components/camera-shake/schema';

export type OndaEntry = { slug: string; title: string; Component: ComponentType<any>; schema: ZodTypeAny };

export const ONDA_DATA: OndaEntry[] = [
  { slug: 'terminal', title: 'Terminal', Component: Terminal, schema: terminalSchema },
  { slug: 'code-block', title: 'CodeBlock', Component: CodeBlock, schema: codeBlockSchema },
  { slug: 'code-diff', title: 'CodeDiff', Component: CodeDiff, schema: diffLineSchema },
  { slug: 'matrix-decode', title: 'MatrixDecode', Component: MatrixDecode, schema: matrixDecodeSchema },
  { slug: 'node-graph', title: 'NodeGraph', Component: NodeGraph, schema: nodeGraphSchema },
  { slug: 'dynamic-grid', title: 'DynamicGrid', Component: DynamicGrid, schema: dynamicGridSchema },
  { slug: 'progress-steps', title: 'ProgressSteps', Component: ProgressSteps, schema: progressStepsSchema },
  { slug: 'split-screen', title: 'SplitScreen', Component: SplitScreen, schema: splitScreenSchema },
  { slug: 'video-clip', title: 'VideoClip', Component: VideoClip, schema: videoClipSchema },
  { slug: 'audio-clip', title: 'AudioClip', Component: AudioClip, schema: audioClipSchema },
  { slug: 'audio-visualizer', title: 'AudioVisualizer', Component: AudioVisualizer, schema: audioVisualizerSchema },
  { slug: 'captions', title: 'Captions', Component: Captions, schema: captionsSchema },
  { slug: 'pulsing-indicator', title: 'PulsingIndicator', Component: PulsingIndicator, schema: pulsingIndicatorSchema },
  { slug: 'confetti', title: 'Confetti', Component: Confetti, schema: confettiSchema },
  { slug: 'rgb-glitch-text', title: 'RgbGlitchText', Component: RgbGlitchText, schema: rgbGlitchTextSchema },
  { slug: 'gradient-shift', title: 'GradientShift', Component: GradientShift, schema: gradientShiftSchema },
  { slug: 'grain-overlay', title: 'GrainOverlay', Component: GrainOverlay, schema: grainOverlaySchema },
  { slug: 'vignette', title: 'Vignette', Component: Vignette, schema: vignetteSchema },
  { slug: 'camera-shake', title: 'CameraShake', Component: CameraShake, schema: cameraShakeSchema },
];

export const ONDA_DATA_MAP: Record<string, OndaEntry> = Object.fromEntries(ONDA_DATA.map((e) => [e.slug, e]));
