#!/usr/bin/env python3
"""
build_cli_d3_reels.py — batch-build CLI-explainer review cuts for D3 sims.

The input beats wear the CLAUDE Remotion template (ClaudeComposerAsk /
ClaudeCodeBeat / ClaudeTitleOutro — cream, warm ink, terracotta), never the
Onda/bash terminal. The reel reconstructs how the sim was BUILT with Claude:
show the prompt (B02), show the ACTUAL code from the sim's own HTML (B03),
show the output (B04/B06).

For each sim in a JSON config:
  1. Write beat_sheet.json (Liam / am_onyx / claude palette; canonical
     shot.remotion.pattern format so remotion_scenes.py can render the beats)
  2. capture_sim.py → media/output.mp4 + media/change.mp4
  3. Copy to media/B04.mp4 and media/B06.mp4
  4. generate_audio_kokoro.py --no-gate
  5. remotion_scenes.py → media/B00/B02/B03/B08/B09.mp4 (Claude-skin beats;
     soft-fail: un-rendered beats compile as slates)
  6. compile.py --review
  7. Append result to log file

Usage:
  python3 build_cli_d3_reels.py <config.json> [--log <log_file>]

Config JSON:
  {
    "sims": [
      {
        "slug": "00-wave-packet-spreading",
        "book": "quantum-mechanics-with-llms",
        "html": "/path/to/sim.html",
        "note": "physics note from log",
        "title": "Wave Packet Spreading with Claude"   # optional
      }, ...
    ]
  }
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

BOOKS_DIR = Path(__file__).resolve().parents[3]   # books/
ART_HOME  = Path(__file__).resolve().parents[2]   # brutalist-art/
SCRIPTS   = Path(__file__).resolve().parent       # runtime/scripts/
DEFAULT_LOG = BOOKS_DIR / "CLI-EXPLAINERS-OVERNIGHT-LOG.md"

GREETINGS = [
    "Hey", "Hola", "Ciao", "Salut", "Yo", "Oi", "Merhaba",
    "Szia", "Ahoj", "Hei", "Hej", "Olá", "Namaste", "Yalla", "Annyeong",
    "Aloha", "Shalom", "Ciao", "Bonjour", "G'day",
]


def greeting_for(slug: str) -> str:
    return GREETINGS[abs(hash(slug)) % len(GREETINGS)]


def make_title(slug: str, note: str) -> str:
    concept = note.split(";")[0].strip()
    concept = concept[:1].upper() + concept[1:]
    return f"{concept} — with Claude"


def extract_code(html_path: Path, max_lines: int = 20, max_width: int = 78) -> str:
    """Pull the ACTUAL code out of the sim's single-file HTML for the CODE beat.

    THE ACTUAL-CODE LAW (terminal-screencast skill): the CODE beat shows the
    real source that ran — the sim's own inline JS, trimmed to what teaches —
    never pseudocode. Heuristic: take the longest inline <script> block, skip
    the d3 CDN import lines, and keep the first `max_lines` meaningful lines.
    """
    try:
        html = html_path.read_text(errors="replace")
    except OSError:
        return "// source unavailable"

    import re
    blocks = re.findall(r"<script(?![^>]*\bsrc=)[^>]*>(.*?)</script>",
                        html, re.DOTALL | re.IGNORECASE)
    if not blocks:
        return "// no inline script found"
    js = max(blocks, key=len)

    lines, blank_run = [], 0
    for raw in js.splitlines():
        line = raw.rstrip()
        if not line.strip():
            blank_run += 1
            if blank_run > 1 or not lines:
                continue
        else:
            blank_run = 0
        if len(line) > max_width:
            line = line[: max_width - 1] + "…"
        lines.append(line)
        if len(lines) >= max_lines:
            break

    code = "\n".join(lines).strip()
    return (f"// {html_path.name} — generated by Claude Code (trimmed)\n"
            f"{code}\n// … trimmed — full source: {html_path.name}")


def remotion_shot(pattern: str, props: dict, beat_id: str) -> dict:
    """Canonical Remotion shot — the format remotion_scenes.py + compile.py read."""
    return {
        "type": "GRAPHIC",
        "source": "remotion",
        "motion": "fade",
        "remotion": {
            "pattern": pattern,
            "provenance": f"proven-core/{pattern}",
            "version": "1",
            "props": props,
            "rendered": {"out": f"media/{beat_id}.mp4", "at": ""},
        },
    }


def make_beat_sheet(sim: dict, reel_slug: str, code: str) -> dict:
    slug   = sim["slug"]
    note   = sim.get("note", "a quantum physics simulation")
    title  = sim.get("title") or make_title(slug, note)

    greeting = greeting_for(slug)

    concept = note.split(";")[0].strip()
    claims = [p.strip() for p in note.split(";")]
    key_claim = ""
    for c in reversed(claims):
        if "verified" in c.lower():
            key_claim = c.replace(" verified", "").strip()
            break
    if not key_claim and len(claims) > 1:
        key_claim = claims[-1].replace(" verified", "").strip()

    b00 = (f"{greeting}. This is Liam, in for Bear. "
           f"One Claude prompt. A live interactive simulation of {concept.lower()}.")

    b01 = (f"Quantum mechanics is full of non-obvious results. "
           f"Today's: {concept}. "
           f"{('Key checkable number: ' + key_claim + '.') if key_claim else ''} "
           f"Let us build the demonstration.")

    b02_prompt = (
        f"Build me an interactive D3 simulation of {concept.lower()}. "
        f"Use D3 version 7 from CDN. Single-file HTML, all physics computed "
        f"in-browser JavaScript. Add at least one slider or control. "
        f"Teardown palette: background #FFFFFF, ink #2A1A0E, accent #C8102E."
    )

    b03 = ("Claude returns a single-file HTML. "
           "D3 version 7. All the physics runs in the browser. "
           "No server. No build step.")

    b04 = (f"Here is the baseline — the simulation at rest. "
           f"{concept}.")

    b05 = ("Now interact with the control — drag the slider, click the toggle. "
           "Watch the physics respond.")

    b06 = (f"The simulation updates in real time. "
           f"{(key_claim + '. ') if key_claim else ''}"
           f"Exactly as the equations predict.")

    b07 = (f"One prompt. A live quantum mechanics demonstration. "
           f"{concept}. "
           f"Bear reviews these in the morning and ships the ones that pass.")

    b08_prompt = (
        f"Extend this {slug.replace('-', ' ')} simulation. "
        f"Add a second control that changes [parameter]. "
        f"Show how it affects the result."
    )
    b08 = f"Your turn. {b08_prompt}"

    b09 = "Liam, in for Bear."

    # Shared Claude-skin props (fidelity palette — never retinted)
    topic   = "CLAUDE CODE · D3"
    segment = (concept[:1].upper() + concept[1:])[:48]

    return {
        "metadata": {
            "slug": reel_slug,
            "title": title,
            "series": "Claude for Science",
            "channel": "claude-liam",
            "greeting": greeting,
            "voice_kokoro": "am_onyx",
            "engine": "kokoro",
            "palette": "claude",
            "register": "Teardown",
        },
        "beats": [
            {
                # COLD OPEN LAW — the Claude UI first, ask shown answered
                "beat_id": "B00", "act": "INTRO",
                "narration_text": b00,
                "shot": remotion_shot("ClaudeComposerAsk", {
                    "command": f'claude "build an interactive D3 sim of {concept.lower()}"',
                    "topic": topic, "segment": segment,
                    "greeting": f"{greeting}, Liam",
                    "runningText": "running simulation…",
                    "output": [f"{slug}.html written",
                               "D3 v7 · single file · physics in-browser",
                               "open it — it runs"],
                }, "B00"),
                "estimated_duration_s": 5.0,
            },
            {
                "beat_id": "B01", "act": "PROBLEM",
                "narration_text": b01,
                "shot": {"type": "slate"},
                "estimated_duration_s": 8.0,
            },
            {
                "beat_id": "B02", "act": "ASK",
                "narration_text": "Here is the prompt.",
                "shot": remotion_shot("ClaudeComposerAsk", {
                    "command": f'claude "{b02_prompt}"',
                    "topic": topic, "segment": segment,
                    "greeting": "",
                    "runningText": "building the sim…",
                }, "B02"),
                "estimated_duration_s": 5.0,
            },
            {
                # ACTUAL-CODE LAW — the sim's real JS, trimmed to what teaches
                "beat_id": "B03", "act": "CODE",
                "narration_text": b03,
                "shot": remotion_shot("ClaudeCodeBeat", {
                    "title": f"{slug}.html",
                    "code": code,
                    "sparkLine": "Read before running.",
                }, "B03"),
                "estimated_duration_s": 5.0,
            },
            {
                "beat_id": "B04", "act": "OUTPUT",
                "narration_text": b04,
                "shot": {"type": "video", "source": "media/B04.mp4"},
                "estimated_duration_s": 6.0,
            },
            {
                "beat_id": "B05", "act": "CHANGE",
                "narration_text": b05,
                "shot": {"type": "slate"},
                "estimated_duration_s": 5.0,
            },
            {
                "beat_id": "B06", "act": "OUTPUT",
                "narration_text": b06,
                "shot": {"type": "video", "source": "media/B06.mp4"},
                "estimated_duration_s": 8.0,
            },
            {
                "beat_id": "B07", "act": "SUMMARY",
                "narration_text": b07,
                "shot": {"type": "slate"},
                "estimated_duration_s": 7.0,
            },
            {
                # HANDOFF LAW — suggested prompt typed in, viewer-addressed
                "beat_id": "B08", "act": "NEXT STEPS",
                "narration_text": b08,
                "shot": remotion_shot("ClaudeComposerAsk", {
                    "command": f'claude "{b08_prompt}"',
                    "topic": topic, "segment": segment,
                    "greeting": "Your turn.",
                    "runningText": "paste this into Claude…",
                }, "B08"),
                "estimated_duration_s": 6.0,
            },
            {
                # OUTRO LAW — restate the episode title, terracotta period
                "beat_id": "B09", "act": "OUTRO",
                "narration_text": b09,
                "shot": remotion_shot("ClaudeTitleOutro", {
                    "title": title if title.rstrip() and title.rstrip()[-1] in ".?!\u2026" else f"{title}.",
                    "handle": "@NikBearBrown",
                    "subline": "Liam, in for Bear",
                }, "B09"),
                "estimated_duration_s": 3.0,
            },
        ],
    }


def run(cmd, timeout=600, env=None):
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout,
                       env=env or os.environ.copy())
    out = (r.stdout + "\n" + r.stderr).strip()
    return r.returncode, out


def append_log(log_file: Path, slug, book, lane, status, mp4, note):
    line = f"| {slug} | {book} | {lane} | {status} | {mp4} | {note} |\n"
    with open(log_file, "a") as f:
        f.write(line)


def build_one(sim: dict, log_file: Path) -> str:
    slug      = sim["slug"]
    book      = sim["book"]
    html_path = Path(sim["html"])
    reel_slug = f"claude-liam-cli-{slug}"
    reel_dir  = BOOKS_DIR / book / "youtube" / reel_slug

    review_mp4 = reel_dir / f"{reel_slug}-slate.mp4"
    if review_mp4.exists() and review_mp4.stat().st_size > 50_000:
        note = f"already built ({review_mp4.stat().st_size // 1024}KB)"
        print(f"[build] SKIP {reel_slug}  ({note})", flush=True)
        append_log(log_file, slug, book, "D3", "SKIP", str(review_mp4), note)
        return "SKIP"

    print(f"\n{'='*60}", flush=True)
    print(f"[build] START  {reel_slug}", flush=True)

    env = os.environ.copy()
    env["ART_HOME"] = str(ART_HOME)

    try:
        if not html_path.exists():
            raise RuntimeError(f"HTML not found: {html_path}")

        reel_dir.mkdir(parents=True, exist_ok=True)
        (reel_dir / "media").mkdir(exist_ok=True)
        (reel_dir / "mp3").mkdir(exist_ok=True)

        code = extract_code(html_path)
        bs = make_beat_sheet(sim, reel_slug, code)
        (reel_dir / "beat_sheet.json").write_text(json.dumps(bs, indent=2))
        print(f"[build] beat_sheet.json written (Claude skin, actual code)", flush=True)

        print(f"[build] capturing {slug}...", flush=True)
        rc, out = run(
            ["python3", str(SCRIPTS / "capture_sim.py"), str(html_path), str(reel_dir)],
            timeout=240, env=env,
        )
        if rc != 0:
            raise RuntimeError(f"capture_sim: {out[-400:]}")
        out_mp4  = reel_dir / "media" / "output.mp4"
        chg_mp4  = reel_dir / "media" / "change.mp4"
        if not (out_mp4.exists() and chg_mp4.exists()):
            raise RuntimeError("capture_sim produced no output mp4")
        print(f"[build] captured output={out_mp4.stat().st_size//1024}KB "
              f"change={chg_mp4.stat().st_size//1024}KB", flush=True)

        shutil.copy(out_mp4,  reel_dir / "media" / "B04.mp4")
        shutil.copy(chg_mp4,  reel_dir / "media" / "B06.mp4")

        print(f"[build] generating audio...", flush=True)
        rc, out = run(
            ["python3", str(SCRIPTS / "generate_audio_kokoro.py"),
             str(reel_dir), "--no-gate"],
            timeout=600, env=env,
        )
        if rc != 0:
            raise RuntimeError(f"audio: {out[-400:]}")
        print(f"[build] audio done", flush=True)

        # Render the Claude-skin Remotion beats (B00/B02/B03/B08/B09) to
        # media/<BID>.mp4. Soft-fail: compile.py falls back to slates for
        # any beat that didn't render.
        print(f"[build] rendering Claude Remotion beats...", flush=True)
        rc, out = run(
            ["python3", str(SCRIPTS / "remotion_scenes.py"), str(reel_dir)],
            timeout=900, env=env,
        )
        if rc != 0:
            print(f"[build] WARN remotion_scenes failed — Claude beats stay "
                  f"slates: {out[-300:]}", flush=True, file=sys.stderr)

        print(f"[build] compiling review cut...", flush=True)
        rc, out = run(
            ["python3", str(SCRIPTS / "compile.py"), str(reel_dir), "--review"],
            timeout=600, env=env,
        )

        # final cut too — clean master when no slates remain (soft-fail otherwise)
        run(["python3", str(SCRIPTS / "compile.py"), str(reel_dir)],
            timeout=600, env=env)
        if rc != 0:
            raise RuntimeError(f"compile: {out[-400:]}")

        if not review_mp4.exists():
            raise RuntimeError(f"review mp4 not found at {review_mp4}")
        size = review_mp4.stat().st_size
        if size < 50_000:
            raise RuntimeError(f"review mp4 suspiciously small: {size} bytes")

        note = f"{size // 1024}KB"
        print(f"[build] DONE  {reel_slug}  ({note})", flush=True)
        append_log(log_file, slug, book, "D3", "BUILT", str(review_mp4), note)
        return "BUILT"

    except Exception as e:
        note = str(e)[:250].replace("|", "/").replace("\n", " ")
        print(f"[build] FAIL  {reel_slug}: {note}", flush=True, file=sys.stderr)
        append_log(log_file, slug, book, "D3", "FAILED", "-", note)
        return f"FAILED: {note}"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("config", help="JSON config with sim list")
    ap.add_argument("--log", default=str(DEFAULT_LOG))
    a = ap.parse_args()

    cfg = json.loads(Path(a.config).read_text())
    sims = cfg["sims"]
    log  = Path(a.log)

    print(f"[build_cli_d3_reels] {len(sims)} sims  log={log}", flush=True)

    counts = {}
    for i, sim in enumerate(sims):
        print(f"\n[build_cli_d3_reels] [{i+1}/{len(sims)}] {sim['slug']}", flush=True)
        result = build_one(sim, log)
        key = result.split(":")[0]
        counts[key] = counts.get(key, 0) + 1

    print(f"\n[build_cli_d3_reels] FINISHED: {counts}", flush=True)


if __name__ == "__main__":
    main()
